apiVersion: v1
kind: Service
metadata:
  name: factorio
spec:
  type: LoadBalancer
  selector:
    app: factorio
  ports:
    - port: 34197
      targetPort: 34197
      protocol: UDP
      name: factorio-udp
    - port: 27015
      targetPort: 27015
      protocol: TCP
      name: factorio-tcp
  externalIPs:
    - 172.16.1.10

