apiVersion: v1
kind: Service
metadata:
  name: minecraft
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: minecraft
  ports:
    - port: 25565
      targetPort: 25565
      protocol: UDP
      name: minecraft-udp
    - port: 25565
      targetPort: 25565
      protocol: TCP
      name: minecraft-tcp
  externalIPs:
    - 172.16.1.25

